/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class AutoRefactorCoinage extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): AutoRefactorCoinage

  methods: {
    REFACTOR_BOUNDARY(): TransactionObject<string>

    REFACTOR_DIVIDER(): TransactionObject<string>

    _factor(): TransactionObject<string>

    _totalSupply(): TransactionObject<{
      balance: string
      refactoredCount: string
      remain: string
      0: string
      1: string
      2: string
    }>

    addMinter(account: string): TransactionObject<void>

    balances(
      arg0: string,
    ): TransactionObject<{
      balance: string
      refactoredCount: string
      remain: string
      0: string
      1: string
      2: string
    }>

    burn(amount: number | string): TransactionObject<void>

    burnFrom(account: string, amount: number | string): TransactionObject<void>

    decimals(): TransactionObject<string>

    decreaseAllowance(
      spender: string,
      subtractedValue: number | string,
    ): TransactionObject<boolean>

    increaseAllowance(
      spender: string,
      addedValue: number | string,
    ): TransactionObject<boolean>

    isMinter(account: string): TransactionObject<boolean>

    isOwner(): TransactionObject<boolean>

    mint(account: string, amount: number | string): TransactionObject<boolean>

    name(): TransactionObject<string>

    owner(): TransactionObject<string>

    refactorCount(): TransactionObject<string>

    renounceMinter(): TransactionObject<void>

    renounceOwnership(): TransactionObject<void>

    symbol(): TransactionObject<string>

    transferOwnership(newOwner: string): TransactionObject<void>

    factor(): TransactionObject<string>

    totalSupply(): TransactionObject<string>

    balanceOf(account: string): TransactionObject<string>

    setFactor(factor: number | string): TransactionObject<boolean>

    transfer(
      recipient: string,
      amount: number | string,
    ): TransactionObject<boolean>

    allowance(owner: string, spender: string): TransactionObject<string>

    approve(
      spender: string,
      amount: number | string,
    ): TransactionObject<boolean>

    transferFrom(
      sender: string,
      recipient: string,
      amount: number | string,
    ): TransactionObject<boolean>
  }

  events: {
    Approval: ContractEvent<{
      owner: string
      spender: string
      value: string
      0: string
      1: string
      2: string
    }>
    FactorSet: ContractEvent<{
      previous: string
      current: string
      shiftCount: string
      0: string
      1: string
      2: string
    }>
    MinterAdded: ContractEvent<string>
    MinterRemoved: ContractEvent<string>
    OwnershipTransferred: ContractEvent<{
      previousOwner: string
      newOwner: string
      0: string
      1: string
    }>
    Transfer: ContractEvent<{
      from: string
      to: string
      value: string
      0: string
      1: string
      2: string
    }>
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
