/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class ConnectRewardBase extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): ConnectRewardBase

  methods: {
    accumulatedReward(): TransactionObject<string>

    isLayer2(): TransactionObject<boolean>

    isZkopru(): TransactionObject<boolean>

    l2RewardManager(): TransactionObject<string>

    layer2Registry(): TransactionObject<string>

    operator(): TransactionObject<string>

    rewards(): TransactionObject<string>

    seigManager(): TransactionObject<string>

    watchTower(): TransactionObject<string>

    setL2Rewardmanager(_l2RewardManager: string): TransactionObject<void>

    claim(amount: number | string): TransactionObject<void>

    totalReward(): TransactionObject<string>

    balanceOfReward(account: string): TransactionObject<string>

    proposeReward(account: string): TransactionObject<boolean>

    finalizeReward(account: string): TransactionObject<boolean>
  }

  events: {
    ClaimedReward: ContractEvent<{
      from: string
      amount: string
      0: string
      1: string
    }>
    ConnectTokamak: ContractEvent<{
      deployer: string
      zkopru: string
      name: string
      0: string
      1: string
      2: string
    }>
    DecreasedReward: ContractEvent<{
      from: string
      amount: string
      0: string
      1: string
    }>
    IncreasedReward: ContractEvent<{
      from: string
      amount: string
      0: string
      1: string
    }>
    OperatorChanged: ContractEvent<string>
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
