/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class IL2RewardManager extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): IL2RewardManager

  methods: {
    rewardPerProposal(): TransactionObject<string>

    rewardPerFinalize(): TransactionObject<string>

    rewardPerValidate(): TransactionObject<string>

    minimumForProposal(): TransactionObject<string>

    claim(_to: string, _amount: number | string): TransactionObject<void>
  }

  events: {
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
