/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class PowerTONI extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): PowerTONI

  methods: {
    seigManager(): TransactionObject<string>

    wton(): TransactionObject<string>

    currentRound(): TransactionObject<string>

    roundDuration(): TransactionObject<string>

    totalDeposits(): TransactionObject<string>

    winnerOf(round: number | string): TransactionObject<string>

    powerOf(account: string): TransactionObject<string>

    init(): TransactionObject<void>

    start(): TransactionObject<void>

    endRound(): TransactionObject<void>

    onDeposit(
      layer2: string,
      account: string,
      amount: number | string,
    ): TransactionObject<void>

    onWithdraw(
      layer2: string,
      account: string,
      amount: number | string,
    ): TransactionObject<void>
  }

  events: {
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
