/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class WatchLogic extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): WatchLogic

  methods: {
    DEFAULT_ADMIN_ROLE(): TransactionObject<string>

    getRoleAdmin(role: string | number[]): TransactionObject<string>

    getRoleMember(
      role: string | number[],
      index: number | string,
    ): TransactionObject<string>

    getRoleMemberCount(role: string | number[]): TransactionObject<string>

    grantRole(role: string | number[], account: string): TransactionObject<void>

    hasRole(
      role: string | number[],
      account: string,
    ): TransactionObject<boolean>

    layer2Registry(): TransactionObject<string>

    renounceRole(
      role: string | number[],
      account: string,
    ): TransactionObject<void>

    revokeRole(
      role: string | number[],
      account: string,
    ): TransactionObject<void>

    seigManager(): TransactionObject<string>

    zkopruLayer2Factory(): TransactionObject<string>

    setSeigManager(_seigManager: string): TransactionObject<void>

    setLayer2Registry(_layer2Registry: string): TransactionObject<void>

    totalCountWatchers(kind: number | string): TransactionObject<string>

    totalCountLayer2s(kind: number | string): TransactionObject<string>

    isRegisteredZkopru(_zkopru: string): TransactionObject<boolean>

    addZkopru(_zkopru: string): TransactionObject<void>

    addWatcher(
      _watcher: string,
      _kind: number | string,
    ): TransactionObject<void>
  }

  events: {
    AddedWatcher: ContractEvent<string>
    AddedZkopru: ContractEvent<string>
    RoleAdminChanged: ContractEvent<{
      role: string
      previousAdminRole: string
      newAdminRole: string
      0: string
      1: string
      2: string
    }>
    RoleGranted: ContractEvent<{
      role: string
      account: string
      sender: string
      0: string
      1: string
      2: string
    }>
    RoleRevoked: ContractEvent<{
      role: string
      account: string
      sender: string
      0: string
      1: string
      2: string
    }>
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
