/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from './types'

interface EventOptions {
  filter?: object
  fromBlock?: BlockType
  topics?: string[]
}

export class ZkopruTokamakStorage extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions)

  clone(): ZkopruTokamakStorage

  methods: {
    accumulatedReward(): TransactionObject<string>

    isLayer2(): TransactionObject<boolean>

    isZkopru(): TransactionObject<boolean>

    l2RewardManager(): TransactionObject<string>

    layer2Registry(): TransactionObject<string>

    operator(): TransactionObject<string>

    rewards(): TransactionObject<string>

    seigManager(): TransactionObject<string>

    watchTower(): TransactionObject<string>
  }

  events: {
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
  }
}
